# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='FaceFeaturesProtocol',
  syntax='proto3',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eprotocol.proto\x12\x14\x46\x61\x63\x65\x46\x65\x61turesProtocol\"\x86\x01\n\x0c\x44ynamicValue\x12\x44\n\tvariables\x18\x01 \x03(\x0b\x32\x31.FaceFeaturesProtocol.DynamicValue.VariablesEntry\x1a\x30\n\x0eVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"O\n\x0fGetFaceFeatures\x12<\n\x10\x64\x65sired_features\x18\x01 \x01(\x0e\x32\".FaceFeaturesProtocol.FaceFeatures\"3\n\x0ePredictedCeleb\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\"z\n\x1a\x43\x65lebSimilarityPredictions\x12\x1d\n\x15most_similar_face_url\x18\x01 \x01(\t\x12=\n\x0fpredicted_celeb\x18\x02 \x03(\x0b\x32$.FaceFeaturesProtocol.PredictedCeleb\"p\n\x16\x43\x65lebSimilarityFeature\x12V\n\x1c\x63\x65leb_similarity_predictions\x18\x01 \x03(\x0b\x32\x30.FaceFeaturesProtocol.CelebSimilarityPredictions\"\xc5\x01\n\x17GetFaceFeaturesResponse\x12*\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1b.FaceFeaturesProtocol.Error\x12\x1c\n\x14user_cropped_face_id\x18\x02 \x01(\t\x12Q\n\x19\x63\x65leb_similarity_features\x18\x03 \x01(\x0b\x32,.FaceFeaturesProtocol.CelebSimilarityFeatureH\x00\x42\r\n\x0bMessageType\"M\n\x05\x45rror\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.FaceFeaturesProtocol.ErrorType\x12\x15\n\rerror_message\x18\x02 \x01(\t*$\n\x0c\x46\x61\x63\x65\x46\x65\x61tures\x12\x14\n\x10\x43\x45LEB_SIMILARITY\x10\x00*6\n\tErrorType\x12\x11\n\rUNKNOWN_ERROR\x10\x00\x12\x16\n\x12MORE_THAN_ONE_FACE\x10\x01\x42\x02H\x03\x62\x06proto3'
)

_FACEFEATURES = _descriptor.EnumDescriptor(
  name='FaceFeatures',
  full_name='FaceFeaturesProtocol.FaceFeatures',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CELEB_SIMILARITY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=828,
  serialized_end=864,
)
_sym_db.RegisterEnumDescriptor(_FACEFEATURES)

FaceFeatures = enum_type_wrapper.EnumTypeWrapper(_FACEFEATURES)
_ERRORTYPE = _descriptor.EnumDescriptor(
  name='ErrorType',
  full_name='FaceFeaturesProtocol.ErrorType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MORE_THAN_ONE_FACE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=866,
  serialized_end=920,
)
_sym_db.RegisterEnumDescriptor(_ERRORTYPE)

ErrorType = enum_type_wrapper.EnumTypeWrapper(_ERRORTYPE)
CELEB_SIMILARITY = 0
UNKNOWN_ERROR = 0
MORE_THAN_ONE_FACE = 1



_DYNAMICVALUE_VARIABLESENTRY = _descriptor.Descriptor(
  name='VariablesEntry',
  full_name='FaceFeaturesProtocol.DynamicValue.VariablesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='FaceFeaturesProtocol.DynamicValue.VariablesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='FaceFeaturesProtocol.DynamicValue.VariablesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=175,
)

_DYNAMICVALUE = _descriptor.Descriptor(
  name='DynamicValue',
  full_name='FaceFeaturesProtocol.DynamicValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='variables', full_name='FaceFeaturesProtocol.DynamicValue.variables', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DYNAMICVALUE_VARIABLESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=175,
)


_GETFACEFEATURES = _descriptor.Descriptor(
  name='GetFaceFeatures',
  full_name='FaceFeaturesProtocol.GetFaceFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='desired_features', full_name='FaceFeaturesProtocol.GetFaceFeatures.desired_features', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=256,
)


_PREDICTEDCELEB = _descriptor.Descriptor(
  name='PredictedCeleb',
  full_name='FaceFeaturesProtocol.PredictedCeleb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FaceFeaturesProtocol.PredictedCeleb.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='probability', full_name='FaceFeaturesProtocol.PredictedCeleb.probability', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=309,
)


_CELEBSIMILARITYPREDICTIONS = _descriptor.Descriptor(
  name='CelebSimilarityPredictions',
  full_name='FaceFeaturesProtocol.CelebSimilarityPredictions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='most_similar_face_url', full_name='FaceFeaturesProtocol.CelebSimilarityPredictions.most_similar_face_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predicted_celeb', full_name='FaceFeaturesProtocol.CelebSimilarityPredictions.predicted_celeb', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=433,
)


_CELEBSIMILARITYFEATURE = _descriptor.Descriptor(
  name='CelebSimilarityFeature',
  full_name='FaceFeaturesProtocol.CelebSimilarityFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='celeb_similarity_predictions', full_name='FaceFeaturesProtocol.CelebSimilarityFeature.celeb_similarity_predictions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=547,
)


_GETFACEFEATURESRESPONSE = _descriptor.Descriptor(
  name='GetFaceFeaturesResponse',
  full_name='FaceFeaturesProtocol.GetFaceFeaturesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='FaceFeaturesProtocol.GetFaceFeaturesResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_cropped_face_id', full_name='FaceFeaturesProtocol.GetFaceFeaturesResponse.user_cropped_face_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='celeb_similarity_features', full_name='FaceFeaturesProtocol.GetFaceFeaturesResponse.celeb_similarity_features', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MessageType', full_name='FaceFeaturesProtocol.GetFaceFeaturesResponse.MessageType',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=550,
  serialized_end=747,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='FaceFeaturesProtocol.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='FaceFeaturesProtocol.Error.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='FaceFeaturesProtocol.Error.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=749,
  serialized_end=826,
)

_DYNAMICVALUE_VARIABLESENTRY.containing_type = _DYNAMICVALUE
_DYNAMICVALUE.fields_by_name['variables'].message_type = _DYNAMICVALUE_VARIABLESENTRY
_GETFACEFEATURES.fields_by_name['desired_features'].enum_type = _FACEFEATURES
_CELEBSIMILARITYPREDICTIONS.fields_by_name['predicted_celeb'].message_type = _PREDICTEDCELEB
_CELEBSIMILARITYFEATURE.fields_by_name['celeb_similarity_predictions'].message_type = _CELEBSIMILARITYPREDICTIONS
_GETFACEFEATURESRESPONSE.fields_by_name['error'].message_type = _ERROR
_GETFACEFEATURESRESPONSE.fields_by_name['celeb_similarity_features'].message_type = _CELEBSIMILARITYFEATURE
_GETFACEFEATURESRESPONSE.oneofs_by_name['MessageType'].fields.append(
  _GETFACEFEATURESRESPONSE.fields_by_name['celeb_similarity_features'])
_GETFACEFEATURESRESPONSE.fields_by_name['celeb_similarity_features'].containing_oneof = _GETFACEFEATURESRESPONSE.oneofs_by_name['MessageType']
_ERROR.fields_by_name['type'].enum_type = _ERRORTYPE
DESCRIPTOR.message_types_by_name['DynamicValue'] = _DYNAMICVALUE
DESCRIPTOR.message_types_by_name['GetFaceFeatures'] = _GETFACEFEATURES
DESCRIPTOR.message_types_by_name['PredictedCeleb'] = _PREDICTEDCELEB
DESCRIPTOR.message_types_by_name['CelebSimilarityPredictions'] = _CELEBSIMILARITYPREDICTIONS
DESCRIPTOR.message_types_by_name['CelebSimilarityFeature'] = _CELEBSIMILARITYFEATURE
DESCRIPTOR.message_types_by_name['GetFaceFeaturesResponse'] = _GETFACEFEATURESRESPONSE
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.enum_types_by_name['FaceFeatures'] = _FACEFEATURES
DESCRIPTOR.enum_types_by_name['ErrorType'] = _ERRORTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DynamicValue = _reflection.GeneratedProtocolMessageType('DynamicValue', (_message.Message,), {

  'VariablesEntry' : _reflection.GeneratedProtocolMessageType('VariablesEntry', (_message.Message,), {
    'DESCRIPTOR' : _DYNAMICVALUE_VARIABLESENTRY,
    '__module__' : 'protocol_pb2'
    # @@protoc_insertion_point(class_scope:FaceFeaturesProtocol.DynamicValue.VariablesEntry)
    })
  ,
  'DESCRIPTOR' : _DYNAMICVALUE,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:FaceFeaturesProtocol.DynamicValue)
  })
_sym_db.RegisterMessage(DynamicValue)
_sym_db.RegisterMessage(DynamicValue.VariablesEntry)

GetFaceFeatures = _reflection.GeneratedProtocolMessageType('GetFaceFeatures', (_message.Message,), {
  'DESCRIPTOR' : _GETFACEFEATURES,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:FaceFeaturesProtocol.GetFaceFeatures)
  })
_sym_db.RegisterMessage(GetFaceFeatures)

PredictedCeleb = _reflection.GeneratedProtocolMessageType('PredictedCeleb', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTEDCELEB,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:FaceFeaturesProtocol.PredictedCeleb)
  })
_sym_db.RegisterMessage(PredictedCeleb)

CelebSimilarityPredictions = _reflection.GeneratedProtocolMessageType('CelebSimilarityPredictions', (_message.Message,), {
  'DESCRIPTOR' : _CELEBSIMILARITYPREDICTIONS,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:FaceFeaturesProtocol.CelebSimilarityPredictions)
  })
_sym_db.RegisterMessage(CelebSimilarityPredictions)

CelebSimilarityFeature = _reflection.GeneratedProtocolMessageType('CelebSimilarityFeature', (_message.Message,), {
  'DESCRIPTOR' : _CELEBSIMILARITYFEATURE,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:FaceFeaturesProtocol.CelebSimilarityFeature)
  })
_sym_db.RegisterMessage(CelebSimilarityFeature)

GetFaceFeaturesResponse = _reflection.GeneratedProtocolMessageType('GetFaceFeaturesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETFACEFEATURESRESPONSE,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:FaceFeaturesProtocol.GetFaceFeaturesResponse)
  })
_sym_db.RegisterMessage(GetFaceFeaturesResponse)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:FaceFeaturesProtocol.Error)
  })
_sym_db.RegisterMessage(Error)


DESCRIPTOR._options = None
_DYNAMICVALUE_VARIABLESENTRY._options = None
# @@protoc_insertion_point(module_scope)
